backend:
  name: github
  repo: triinuklein/tirts-tigu
  branch: main
  open_authoring: true

media_folder: "assets/uploads"
public_folder: "assets/uploads"

collections:
  - name: "projects"
    label: "Projektid"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index"
    fields:
      - { label: "Pealkiri", name: "title", widget: "string" }
      - { label: "Kuup√§ev", name: "date", widget: "datetime" }
      - { label: "Pilt", name: "image", widget: "image" }
      - { label: "PDF", name: "pdf", widget: "file", allow_multiple: false }
      - { label: "Sisu", name: "body", widget: "markdown" }

