backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "projects"
    label: "Projektid"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    fields:
      - { label: "Pealkiri", name: "title", widget: "string" }
      - { label: "Kuup√§ev", name: "date", widget: "datetime" }
      - { label: "Pilt", name: "image", widget: "image" }
      - { label: "PDF", name: "pdf", widget: "file", allow_multiple: false }
      - { label: "Sisu", name: "body", widget: "markdown" }
editor:
  preview: false

load_config_file: false

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

# Add this:
extra_js:
  - "/admin/manifest.js"
